doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        logging: false

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/Core/'
                prefix: 'Core\'#        auto_generate_proxy_classes: true
                alias: Core
        dql:
            numeric_functions:
                Rand: Core\\Shared\Infraestructure\Doctrine\Misc\Rand

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: ''

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
