{
 "title": "codigito",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "api.access.log.by.method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"codigito.www\"} | json [30m])) by (method)"
    }
   ]
  },
  {
   "title": "api.access.log.by.status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"codigito.www\"} | json [30m])) by (status)"
    }
   ]
  },
  {
   "title": "api.access.log",
   "type": "logs",
   "description": "apache access log para el api",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"codigito.www\"}  | json | line_format \"{{.remoteIP}}:{{.method}}.{{.status}} => {{.request}}\""
    }
   ]
  }
 ]
}