version: '3.3'
#----------------------------------------------------------
# definicion de la red y rango de ips 
#
# 172.27.102 ip net
#----------------------------------------------------------
networks:
    codigo-com-es-network:
        ipam:
            config:
                - subnet: 172.27.102.0/24
services:
    codigo-com-es.api:
        user: "1000:1000"
        build: api
        container_name: 'codigo-com-es.api'
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../api/:/var/www/vhosts/codigo.com.es/
        extra_hosts:
            - 'mariadb:172.27.102.12'
            - 'codigo-com-es.cdn:127.0.0.1'
        hostname: codigo-com-es.api
        networks:
            codigo-com-es-network:
                ipv4_address: 172.27.102.11

    codigo-com-es.mariadb:
        build: mariadb
        container_name: 'codigo-com-es.mariadb'
        ports:
            - 3306:3306
        restart: always
        hostname: codigo-com-es.mariadb
        networks:
            codigo-com-es-network:
                ipv4_address: 172.27.102.12

    codigo-com-es.admin:
         user: "1000:1000"
         build: admin
         container_name: 'codigo-com-es.admin'
         ports:
             - 8002:80
             - 4432:443
         volumes:
             - ../admin/:/var/www/vhosts/codigo.com.es/
         extra_hosts:
             - 'mariadb:172.27.102.12'
             - 'codigo-com-es.api:172.27.102.11'
             - 'codigo-com-es.cdn:172.27.102.11'
         hostname: codigo-com-es.admin
         networks:
             codigo-com-es-network:
                 ipv4_address: 172.27.102.13

    codigo-com-es.www:
         user: "1000:1000"
         build: www
         container_name: 'codigo-com-es.www'
         ports:
             - 8003:80
             - 4433:443
         volumes:
             - ../www/:/var/www/vhosts/codigo.com.es/
         extra_hosts:
             - 'mariadb:172.27.102.12'
             - 'codigo-com-es.api:172.27.102.11'
             - 'codigo-com-es.cdn:172.27.102.11'
         hostname: codigo-com-es.www
         networks:
             codigo-com-es-network:
                 ipv4_address: 172.27.102.14             