DROP DATABASE IF EXISTS `codigito`;
CREATE DATABASE `codigito` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT ALL PRIVILEGES ON `codigito`.* TO `codigito`@localhost IDENTIFIED BY  'codigito' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `codigito`.* TO `codigito`@'%' IDENTIFIED BY  'codigito' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

use `codigito`;
SET FOREIGN_KEY_CHECKS=0;

--
--
--
SET FOREIGN_KEY_CHECKS=1;
