api_login_check:
    path: /api/login_check

controllersApi:
    resource:
        path: ../Core/Context/
        namespace: Core\Context
    type: attribute
controllersClient:
    resource:
        path: ../Core/Client/
        namespace: Core\Client
    type: attribute
