api_login_check:
    path: /api/login_check

controllersApi:
    resource:
        path: ../src/
        namespace: Codigito\
    type: attribute
controllersClient:
    resource:
        path: ../src/Client/
        namespace: Codigito\Client
    type: attribute
