# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #{.".}>------------------------------------------------------------
    #{.".}>- tag for injection
    #{.".}>------------------------------------------------------------
    _instanceof:
        Codigito\Shared\Domain\Command\CommandHandler:
            tags: ['codigito.domain_command_handler']
        Codigito\Shared\Domain\Query\QueryHandler:
            tags: ['codigito.domain_query_handler']
        Codigito\Shared\Domain\Event\DomainEventSubscriber:
            tags: ['codigito.domain_event_subscriber']
    #{.".}>------------------------------------------------------------

    #{.".}>------------------------------------------------------------
    #{.".}>- all src component as service for injection
    #{.".}>------------------------------------------------------------
    Codigito\:
        resource: '../src/'
    #{.".}>------------------------------------------------------------

    #{.".}>------------------------------------------------------------
    #{.".}>- bus selector, query command event
    #{.".}>------------------------------------------------------------
    Codigito\Shared\Domain\Command\CommandBus: '@Codigito\Shared\Infraestructure\Command\CommandStaticBus'
    Codigito\Shared\Domain\Query\QueryBus: '@Codigito\Shared\Infraestructure\Query\QueryStaticBus'

    #{.".}>------------------------------------------------------------
    #{.".}>- all implementations of handlers are passed as argument to
    #{.".}>- each bus - command and query static in memory bus
    #{.".}>------------------------------------------------------------
    Codigito\Shared\Infraestructure\Command\CommandStaticBus:
        arguments:
            $handlers: !tagged codigito.domain_command_handler
    Codigito\Shared\Infraestructure\Query\QueryStaticBus:
        arguments:
            $handlers: !tagged codigito.domain_query_handler
    #{.".}>------------------------------------------------------------

    #{.".}>------------------------------------------------------------
    #{.".}>- cdn service need an explicitly  value
    #{.".}>------------------------------------------------------------
    Codigito\Shared\Infraestructure\Service\CdnLocalCreator:
        arguments: ["%env(CDN_BASEDIR)%"]
    #{.".}>------------------------------------------------------------

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # RabbitMQ
    Codigito\Shared\Infraestructure\Rabbitmq\RabbitMqConnection:
      arguments:
        - host: '%env(RABBITMQ_HOST)%'
          port: '%env(RABBITMQ_PORT)%'
          vhost: '%env(RABBITMQ_MOOC_VHOST)%'
          login: '%env(RABBITMQ_LOGIN)%'
          password: '%env(RABBITMQ_PASSWORD)%'
          read_timeout: 2
          write_timeout: 2
          connect_timeout: 5

    Codigito\Shared\Infraestructure\Rabbitmq\RabbitMqEventBus:
      arguments: ['@Codigito\Shared\Infraestructure\Rabbitmq\RabbitMqConnection', '%env(RABBITMQ_EXCHANGE)%']

#  Codigito\Shared\Infraestructure\Rabbitmq\RabbitMqDomainEventsConsumer:
#    arguments:
#      - '@Codigito\Shared\Infraestructure\Rabbitmq\RabbitMqConnection'
#      - '@Codigito\Shared\Infrastructure\Bus\Event\DomainEventJsonDeserializer'
#      - '%env(RABBITMQ_EXCHANGE)%'
#      - '%env(RABBITMQ_MAX_RETRIES)%'

    Codigito\Shared\Infraestructure\Command\ConfigureRabbitMqCommand:
      arguments:
        - '@Codigito\Shared\Infraestructure\Rabbitmq\RabbitMqConfigurer'
        - '%env(RABBITMQ_EXCHANGE)%'
        - !tagged codigito.domain_event_subscriber

    # -- IMPLEMENTATIONS SELECTOR --
    Codigito\Shared\Domain\Event\DomainEventBus: '@Codigito\Shared\Infraestructure\Rabbitmq\RabbitMqEventBus'