apiVersion: 1

datasources:
- name: codigito.mariadb
  type: mysql
  url: codigito.mariadb:3306
  user: codigito
  jsonData:
    database: codigito
    maxOpenConns: 100 # Grafana v5.4+
    maxIdleConns: 100 # Grafana v5.4+
    maxIdleConnsAuto: true # Grafana v9.5.1+
    connMaxLifetime: 14400 # Grafana v5.4+
  secureJsonData:
    password: codigito
